// export const About = () => {
//     return <div>About Page</div>
// }


// 14.Lazy Loading
const About = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id leo consectetur purus iaculis interdum ut nec enim. Sed nibh tellus, varius ut tempor ut, congue vitae tellus. Vivamus a massa eu enim pellentesque tincidunt. Duis gravida id ante ut tempus. Nullam neque sapien, interdum ut ante ut, maximus maximus neque. Sed mauris erat, fringilla a sapien nec, accumsan accumsan lectus. Proin quis tempor tortor, non consequat libero. Proin nec elit at ante vulputate tincidunt. Morbi ultricies, est nec posuere auctor, mauris ipsum maximus eros, sed vestibulum nulla ipsum sed nisi. Proin efficitur lectus vestibulum luctus fermentum.

            Donec consequat imperdiet purus. Suspendisse auctor consectetur commodo. Maecenas ut risus vitae nibh condimentum cursus. Suspendisse agravida ipsum, et vestibulum odio. Ut eget ultrices ante. Sed facilisis laoreet quam quis placerat. Curabitur pellentesque, odio id iaculisultricies, nisi tellus euismod elit, id sodales erat ipsum vel risus. Cras felis leo, placerat quis vulputate nec, sodales sit amet ligula.Pellentesque a leo risus. Donec mattis urna a fringilla facilisis. Ut volutpat pharetra tincidunt. Nulla fermentum dolor risus, ac congue elitultrices vel. Fusce a vulputate leo. Etiam nisi ante, finibus sed venenatis at, malesuada fermentum erat.

            Phasellus vitae bibendum ante, sit amet pretium elit. Sed fringilla faucibus euismod. Ut congue orci quis risus mollis tristique. Quisque inaccumsan elit. Proin eget orci vitae dui malesuada tristique vel sit amet ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sediaculis vehicula arcu. Vestibulum elementum nulla arcu, eget pulvinar libero egestas vel. Vivamus diam sem, eleifend ut tempor ac, hendrerit non ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus faucibus dui a urna sagittis mollis. Sed vitae maximus mauris.Lorem ipsum dolor sit amet, consectetur adipiscing elit.

            Mauris ultricies eleifend augue viverra viverra. Nam quis enim orci. Integer ut enim justo. Cras vitae consequat diam. Etiam urna sapien,volutpat nec venenatis id, lobortis non nisl. Morbi sagittis nisi id vehicula fermentum. Sed varius eros vitae felis fringilla scelerisque. Nam dignissim, justo mollis vehicula aliquet, neque metus lacinia ipsum, sed dapibus ex magna at ante. Donec blandit neque nulla, vel viverrametus suscipit ac. Fusce at nisi mattis velit convallis bibendum vitae ac quam. Fusce varius fringilla enim, nec pellentesque mi ultriciessed. Pellentesque non tortor eget neque rutrum aliquam. Nunc sed sollicitudin leo. Ut cursus eget nunc et convallis.

            Vivamus et nisi a nisi scelerisque dictum. Proin blandit tortor in ante ultrices, eu maximus mi venenatis. In iaculis molestie laoreet.Vivamus ac fringilla sem. Quisque bibendum mi nisl, vel dapibus mauris scelerisque id. Fusce in metus ut quam aliquam vehicula sit ametpulvinar diam. Quisque at condimentum felis. Nunc interdum gravida massa sed volutpat. Aliquam id tristique quam. Morbi nec est at justoaliquam convallis quis commodo nisl. Curabitur nisl leo, volutpat viverra porta et, euismod luctus tortor.

            Nulla sollicitudin vestibulum egestas. Etiam et convallis magna. Ut a massa in nunc porttitor posuere. Vivamus volutpat, mauris in hendreritultricies, est nulla viverra justo, nec tincidunt nisl metus vel sapien. Aliquam vel convallis urna. Donec malesuada gravida viverra.Vestibulum mollis congue mi, id auctor lectus. Integer diam metus, bibendum ac viverra at, bibendum vel dui. Morbi pharetra diam sapien.Mauris semper porta hendrerit. Praesent rhoncus euismod ligula, sodales efficitur turpis tempus id. Nunc quis felis sed leo sollicitudinultricies non vel orci. Aenean viverra lacus maximus leo iaculis egestas. Mauris odio ipsum, posuere eget eros ac, iaculis bibendum lorem.

            Cras massa dolor, eleifend ac eros et, sollicitudin ornare magna. Nulla mattis tellus efficitur urna egestas efficitur. Proin tinciduntconvallis gravida. Maecenas et maximus ligula, a bibendum quam. Cras dapibus feugiat libero, in hendrerit metus volutpat at. Integer sit ameteros in arcu venenatis finibus. Integer bibendum interdum lacinia. In diam lectus, iaculis et neque sit amet, iaculis posuere augue. Proinnulla elit, mollis ac dui at, ultrices egestas tortor. Aliquam laoreet nisi non ipsum lobortis faucibus. Nulla nec nisi massa. Nullasollicitudin ullamcorper leo a suscipit.

            Suspendisse vitae lorem venenatis, dictum neque a, congue tortor. In vel tincidunt arcu. Mauris tincidunt sed dolor dapibus tempor. In magnaenim, tempus in sapien vitae, imperdiet pulvinar enim. Proin nec elementum libero, nec dictum lectus. Nulla accumsan scelerisque libero acelementum. Vivamus elit lorem, auctor sit amet lacus nec, luctus pulvinar mi. Sed pellentesque scelerisque turpis vel tincidunt. Donec dictumlacinia lectus, in semper eros ultricies ut. Cras quis ipsum et lectus blandit congue. Cras pulvinar, sem eget viverra sagittis, libero arcupharetra leo, ut dapibus tellus dolor a mi. Duis non vestibulum nulla. Nulla fringilla dui sed metus convallis vulputate. In euismod sit ametmagna eget ullamcorper. Nulla in lacus est. Cras vitae congue magna.

            Curabitur magna nunc, molestie at molestie vitae, dignissim non dolor. Proin ullamcorper quam et nunc suscipit, eget aliquam metus lacinia.Pellentesque malesuada elit vel faucibus tincidunt. Cras metus elit, faucibus sed mi ut, laoreet commodo justo. Etiam rhoncus non massa ac faucibus. Integer in efficitur leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam sagittis est non maximus tempus.Donec pellentesque vitae nulla ut euismod. Mauris porta lorem odio, interdum efficitur augue rhoncus semper. Praesent mattis eu lacus egettincidunt. Fusce tempor ullamcorper nisl, eu fermentum nulla dictum non. Quisque lobortis porttitor egestas. Morbi efficitur porttitor magna vitae pulvinar.

            Proin sagittis maximus sapien, id dignissim nunc porttitor eget. Vestibulum ac nunc nec risus egestas rutrum pellentesque id lacus. Aenean a enim sed arcu sodales varius ac eget nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pharetra finibus magna vitae semper. Pellentesque commodo rhoncus placerat. Suspendisse eleifend elementum commodo. Nunc ac lorem gravida, lacinia massa quis, maximus nulla. Proin a elementum est, nec tempor magna. In volutpat sapien non ante pretium, eu molestie urna porta.

            Ut non congue turpis. Aliquam id aliquam neque. Phasellus vitae turpis eu ex elementum lacinia. Curabitur sagittis consequat molestie. Donec mattis felis a eros auctor, vel efficitur felis mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce sit amet faucibus mauris, eget fringilla orci. Mauris fringilla vitae quam nec pharetra. Curabitur diam ante, varius vitae eros sed, semper vestibulum turpis.Sed eleifend elementum sapien sit amet ultrices. Ut tincidunt at augue ut condimentum. Sed lorem enim, iaculis eu mollis sed, efficitur sed nulla. Donec ac urna tincidunt, ultricies erat id, ullamcorper ligula. Nam erat augue, viverra vitae nibh vitae, dictum mattis leo. In hac habitasse platea dictumst. Etiam dignissim lobortis ullamcorper.

            Mauris et nibh nec elit consectetur placerat. Suspendisse congue arcu consectetur nisl molestie sollicitudin. Sed at enim sed nulla elementumblandit. Quisque finibus dapibus metus nec vestibulum. Suspendisse justo lacus, pellentesque ac commodo vitae, auctor a ex. Integer id diamultrices, vulputate eros ac, rutrum neque. Suspendisse id nisi in tortor varius rhoncus mattis id urna. Duis molestie lorem quis dolor tempussemper.

            Nulla sit amet diam accumsan, egestas leo vitae, pretium sem. Sed cursus nisl justo, vitae maximus sapien iaculis dapibus. Aliquam euismod fringilla enim, eget sagittis odio consectetur at. Nulla facilisi. Nulla sit amet pulvinar augue. Duis quis rhoncus lacus. Etiam justo purus,consectetur ac odio nec, aliquam dapibus mauris. Suspendisse volutpat rutrum elit, sit amet tincidunt felis maximus in. Aliquam lacinia, lacusnon efficitur aliquet, nibh metus euismod justo, ac euismod quam magna id enim. Nam convallis auctor aliquet. Orci varius natoque penatibus etmagnis dis parturient montes, nascetur ridiculus mus.

            Aliquam erat volutpat. Phasellus volutpat augue et fringilla tincidunt. Pellentesque dignissim eros lacus, in condimentum felis scelerisqueet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas porttitor dui ligula, et laoreetdiam dapibus at. Mauris luctus neque vel mauris ultricies fringilla. Mauris aliquam nunc quis nibh euismod imperdiet. Cras auctor malesuadaante at lacinia. Donec sed tincidunt odio, nec viverra sapien. Pellentesque ut condimentum mauris, non maximus sem. Sed vel massa id liberosollicitudin semper. Duis faucibus vehicula consectetur. Nullam congue mauris sed risus vehicula pulvinar. Vivamus porta ex vitae nuncultrices sollicitudin. Maecenas mattis sit amet mauris quis dignissim.

            Nulla facilisi. Vivamus vel lectus tempor velit auctor dapibus. Mauris facilisis sapien felis. Praesent facilisis augue id ligula vulputate,ut interdum nulla tincidunt. In hac habitasse platea dictumst. Curabitur vehicula turpis at ipsum ullamcorper, et maximus ex volutpat. Morbiac nibh a lacus auctor interdum. Nullam dictum, neque et vestibulum viverra, diam massa pretium nisi, a tincidunt sapien nibh at mi. Vivamussit amet neque vitae nisi aliquet vehicula id eget diam. Nullam fringilla mauris neque, et varius massa porta at. Suspendisse suscipit arcuvel ligula vehicula rhoncus. Donec commodo diam magna, in iaculis augue dapibus et.

            Donec tempus rhoncus orci at sagittis. Morbi vel tellus eu lorem euismod malesuada. Orci varius natoque penatibus et magnis dis parturientmontes, nascetur ridiculus mus. Praesent feugiat velit convallis congue tincidunt. Aenean placerat nibh ut orci dignissim accumsan. Nullam sedvelit vehicula, semper nulla id, dignissim sapien. Morbi consectetur felis at dui venenatis, in consequat turpis varius. Ut elementum felissed nulla fringilla, id luctus tellus vehicula.

            Suspendisse sollicitudin erat vel metus egestas consequat. In quis sodales augue, eget convallis ligula. Praesent rutrum augue blandit loremvulputate ornare. Maecenas justo tellus, pellentesque nec enim et, facilisis lacinia ligula. Curabitur a egestas libero, vitae ultrices est.Sed lobortis fringilla ante, sit amet imperdiet ligula. Donec blandit, metus et tempus iaculis, ex elit placerat lectus, ac scelerisque quammi in erat. Vestibulum malesuada dapibus ipsum, at ornare ex efficitur malesuada. Vestibulum nunc sem, ornare quis enim sodales, portadignissim urna. Vivamus mollis metus nisi, a posuere nibh porta a.

            Curabitur eget orci turpis. Vestibulum sollicitudin, purus quis suscipit tristique, lectus lacus consequat augue, eget lobortis ante tortor non est. Aliquam at dolor a turpis vehicula lobortis. Integer id lacinia dolor. Mauris ac convallis ligula. Pellentesque posuere elit neque,vitae venenatis nulla consequat ac. Donec augue orci, gravida ac vehicula a, lacinia sit amet felis. Curabitur eget eros tellus. Duis imperdiet, nisl id auctor condimentum, ante ligula convallis nisl, eget fringilla nulla metus vel tortor. Nam dictum ipsum at tortor facilisis pulvinar. Suspendisse lorem dui, ultrices ut ornare ut, luctus quis urna. Sed nec libero tellus. Nulla a sodales massa. Suspendisse potenti.Mauris euismod luctus lacus.

            Nullam pellentesque placerat gravida. Suspendisse massa ligula, laoreet sit amet tellus sit amet, ultricies aliquam metus. Suspendisse pulvinar mollis placerat. Maecenas at mollis orci, nec blandit dolor. Sed fermentum euismod lacus vel scelerisque. Sed elementum ac dolor a mattis. Aliquam nec erat quis sapien convallis faucibus. Proin imperdiet nunc a hendrerit porta. Duis faucibus neque risus, et elementum augue sagittis tincidunt. Aliquam quis erat sed massa sollicitudin dapibus. Donec at turpis posuere metus viverra imperdiet nec aliquet neque. Etiam consequat neque mi, in finibus lacus ultrices at. Donec rhoncus interdum sapien at mattis. Aliquam tempus vitae leo id dictum.

            Donec sodales ut ligula sed imperdiet. Mauris ullamcorper ligula at lacinia mollis. Fusce blandit sed tortor vitae condimentum. In quis dictum orci, sit amet aliquet risus. Fusce vitae purus erat. Donec porta tempus magna, eget pellentesque nulla consequat vitae. Vivamus accumsan magna purus, molestie commodo elit volutpat in. Vestibulum molestie quam eget dapibus lacinia. Sed justo ipsum, euismod vel nulla iaculis,molestie lobortis metus. Cras consequat egestas ex vitae fringilla. Nullam ultrices eros eros, sed efficitur quam semper in. Etiam in laoreet purus. Quisque vitae lectus posuere, ultrices mi ac, condimentum lacus. Praesent iaculis congue mauris, eget convallis metus posuere eu. Etiam consectetur accumsan tempor.
        </div>
    )
        
}
  
export default About;